[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
fantoccini = "0.22.0"
indicatif = "0.17.11"
rand = "0.9.1"
rayon = "1.10.0"
tokio = { version = "1.46.1", features = ["full"] }
